const { CAPABILITIES, ALL_CAPABILITIES } = require('./capabilities');
const { ENTITLEMENTS, ALL_ENTITLEMENTS, ENTITLEMENT_IDS } = require('./entitlements');
const { FEATURE_FLAGS, ALL_FEATURE_FLAGS, DEFAULT_FLAG_VALUES } = require('./feature-flags');
const { DASHBOARD_SECTIONS, ALL_DASHBOARD_SECTIONS, GATING_MATRIX } = require('./dashboard-sections');

module.exports = {
  CAPABILITIES,
  ALL_CAPABILITIES,
  ENTITLEMENTS,
  ALL_ENTITLEMENTS,
  ENTITLEMENT_IDS,
  FEATURE_FLAGS,
  ALL_FEATURE_FLAGS,
  DEFAULT_FLAG_VALUES,
  DASHBOARD_SECTIONS,
  ALL_DASHBOARD_SECTIONS,
  GATING_MATRIX
};
